#!/usr/bin/env perl
use Mojolicious::Lite;
use Data::Dumper;

get '/' => sub {
    my $c = shift;
    my $env = $c->req->env;
    $c->stash(env => $env);
    $c->render(template => 'index');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'HTTP ENV Checker';
<% if (0 == keys(%{$env})) { %>
<p>No http environment.</p>
<% } %>
<% for my $key (keys(%{$env})) { %>
<%= $key %> : <%= $env->{$key} %>
<% } %>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
    <head><title><%= title %></title></head>
    <body><%= content %></body>
</html>
