#!/usr/bin/env perl
use Mojolicious::Lite;
use Data::Dumper;

get '/' => sub {
    my $c = shift;
    my $env = $c->req->env;
    $c->stash(env => $env);
    $c->render(template => 'index');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'HTTP ENV Checker';
<% if (0 == keys(%{$env})) { %>
    <p>No http environment.</p>
<% } else { %>
    <table class="pure-table pure-table-horizontal">
    <thead>
        <tr><th>Name</th><th>Value</th></tr>
    </thead>
    <tbody>
    <% for my $key (keys(%{$env})) { %>
        <tr><td><%= $key %></td><td><%= $env->{$key} %></td></tr>
    <% } %>
    </tbody>
    </table>
<% } %>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><%= title %></title>
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    </head>
    <body><%= content %></body>
</html>
